package com.psycodeinteractive.spacecraftlibrary.presentation.feature.spacecraftlist

import com.psycodeinteractive.spacecraftlibrary.presentation.navigation.PresentationDestination

object SpacecraftListPresentationDestination : PresentationDestination
